                
name: Build Set bxyq3mrghx
on: 
  push:
 
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-o3vv7ekub5,v-07lbvi11k0,v-glfhdopqnd,v-k76xkg3hcv,v-1igzdtub4p]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v02:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-b7btttxbt9,v-dkb2z12ddf,v-ne3loi7zki,v-2npsf9flul,v-3uidjheu2l]
    continue-on-error: true
    needs: build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls
